name: graphilia_board
description: "A fully customizable and interactive drawing board for Flutter."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  meta: ^1.12.0
  perfect_freehand:
    path: ../../../opensource/perfect-freehand-dart
  simpli: ^0.1.1
  value_notifier_tools: ^0.1.2
  r_tree:
    path: ../../../explore/dart/r_tree
  flow_analyzer:
    path: ../flow_analyzer  
  detailed_gesture_detector:
    path: ../detailed_gesture_detector
  math_expressions: ^2.6.0
  one_dollar_unistroke_recognizer: ^1.3.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
