name: graphilia_board
description: "A fully customizable and interactive drawing board for Flutter."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  meta: ^1.12.0
  perfect_freehand:
    git:
      url: https://github.com/Jei-sKappa/perfect-freehand-dart.git
      ref: main
  simpli: ^0.1.1
  value_notifier_tools: ^0.1.2
  r_tree:
    git:
      url: https://github.com/Jei-sKappa/r_tree.git
      ref: master
  flow_analyzer:
    git:
      url: https://github.com/Jei-sKappa/flow-analyzer-dart.git
      ref: main
  detailed_gesture_detector:
    git:
      url: https://github.com/Jei-sKappa/detailed-gesture-detector.git
      ref: main
  math_expressions: ^2.6.0
  one_dollar_unistroke_recognizer: ^1.3.2
  equatable: ^2.0.7
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# dependency_overrides:
#   perfect_freehand:
#     path: ../../../opensource/perfect-freehand-dart
#   r_tree:
#     path: ../../../opensource/r_tree
#   flow_analyzer:
#     path: ../flow_analyzer  
#   detailed_gesture_detector:
#     path: ../detailed_gesture_detector

flutter:
