name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - graphilia_board_core
  - plugins/graphilia_board_canvas_drawing
  - plugins/graphilia_board_widget_drawing
  - plugins/graphilia_board_selected_state
  - plugins/graphilia_board_interaction_feedback