export 'draw_text_on_canvas.dart';
export 'get_point_from_event.dart';
export 'get_vertices_on_rect.dart';
export 'is_between_on_double.dart';
export 'is_inscribed_on_rect.dart';
export 'iterable_removed_x.dart';
export 'log2.dart';
export 'path_from_line_representation.dart';
export 'relative_to_origin_point.dart';
